# Site Build Settings

# jekyll-paginate configurationd
paginate:            10

# Build settings
markdown:            kramdown
highlighter:         rouge
# permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Minwoo Seong"
description:	       "I made this homepage with a minimalist Jekyll theme for running a blog or publication"
author:              "Minwoo Seong"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml

# Analytics
analytics:
  provider               : "google-gtag" 
                          # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-4DG5XL0B3H"
    anonymize_ip         : # true, false (default)
