# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'tjd04862'

menu:
- {name: 'ABOUT ME',  url: 'facts'}
- {name: 'PUBLICATIONS', url: 'publications'}
- {name: 'EXPERIENCES',       url: 'experiences'}
- {name: 'HOBBY & EXTRA ACTIVITIES',      url: 'hobby'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'instagram', link:  'https://www.instagram.com/daily_miniii/'}
- {icon: 'youtube', link:   'https://www.youtube.com/channel/UCUCpgBdsKzO29vFWZjNM-7Q'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
