# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-4DG5XL0B3H'

menu:
- {name: 'About',  url: 'about'}
- {name: 'Publications', url: 'publications'}
- {name: 'Experiences',       url: 'experiences'}
- {name: 'Hobby',      url: 'hobby'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'instagram', link:  'https://www.instagram.com/daily_miniii/'}
- {icon: 'youtube', link:   'https://www.youtube.com/channel/UCUCpgBdsKzO29vFWZjNM-7Q'}
- {icon: 'archive', link:   'https://scholar.google.co.kr/citations?user=MYVwH3MAAAAJ&hl=ko'}
- {icon: 'CV', link:   'https://docs.google.com/document/d/1E9b6_fk1YVqwueIyG-NuD5gBGNsiruUvk8OTOOt7uRs/edit?usp=sharing'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
